# Support the Zen Cart project by donating at: https://zen-cart.com/donate
# Other options are listed below:
custom: ["https://zen-cart.com/donate", "https://paypal.me/drbyte"]
github: [zcwilt,drbyte,ajeh,zencart]
