files:
  - source: /admin/includes/languages/lang.*.php
    translation: /admin/includes/languages/lang.%language%.php
  - source: /admin/includes/languages/english/extra_definitions/*.php
    translation: /admin/includes/languages/%language%/extra_definitions/%original_file_name%
